import Head from 'next/head'
import styled, { css } from 'styled-components';
import Link from 'next/link'

const Nav = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    height: 50px;
    border: 1px solid crimson;
    ${(props) =>
    props.mobile &&
    css`
        width: 100px;
    `}
`;
Nav.displayName = 'Nav';

const NavItem = styled.div`
    color: black;
`;
NavItem.displayName = 'NavItem';

export default function Header() {
    return (
      <>
        <Head>
            <title>Header title</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav>
            <NavItem>
                <Link href="/">
                    <a>HOME</a>
                </Link>
            </NavItem>
            <NavItem>
                <Link href="/contacto">
                    <a>CONTACTO</a>
                </Link>
            </NavItem>
        </Nav>
      </>  
    );
}